# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03c6503fca40af9629c95ddb6bded58003ed1e56a1fe6cf27e6d440a0936601d4e6d72bc9664ec43ba43d80c4378b23ef4f34375e09680be24d7582e1212e47

test:
  secret_key_base: d4ba31df143ef4e64b29f244fdd47c6abc430aee3de772315d9852e6e2e42584b7edaff4cd509a9c1717433e399b80cd0d45c96ff53c9c594afd3f1ecc628945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
